### PR TITLE
File Path displayed in search results

### PR DESCRIPTION
**Pull request by modulexcite**
File Path displayed in search results
Option to open the file in explorer
Modified UI to dark theme to keep it consistent with my ISE
code formatting applied

Also, wanted to thank you for all the excellent articles and the tools you have shared the community. You Rock!

### CODE REVIEW

**Comment by dfinke** [comment]
Thanks for the kind words @modulexcite. Thanks for the PR, looking forward to checking it out. I'll let you know. I was doing a spike on a few different ideas for this. If I get the time and you're interested, I can send it over. Feedback is always welcome.

**Comment by dfinke** [comment]
Colors are cool. Makes it pop. Like the file names too. I indexed all the code in the Microsoft VSCode branch. All the Typescript. Searched for document. Got 91 hits and this error.

```
The property 'Text' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\Douglas\Documents\GitHub\PoShLucene\PoShLucene.ps1:262 char:5
+     $txtPath.Text = $hitDoc.Get("filepath")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException
```

**Comment by modulexcite** [comment]
I apologize for the delayed response.I'm glad you like the colors. I'll grab the code for vscode to index and see if I can replicate the issue. I did however find a different issue I think, I forgot to add a filter for files for the indexing which might be causing the issue you are referring to as well. I'll push a commit later today with a fix.
I've a few ideas myself with the module and I'd be happy to check out the code if you can send it over.

---

Thanks.

```
    _____________________________
```

**Comment by modulexcite** [comment]
pushed a commit with the bugs fixed.
I'm also working on highlighting the text searched by the user when displaying the contents in the UI.

**Comment by dfinke** [comment]
Thank for the update, will check it out soon.

**Pull request merged**
